// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.1
// source: dog.proto

package dog

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetMyDogMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetDog string `protobuf:"bytes,1,opt,name=target_dog,json=targetDog,proto3" json:"target_dog,omitempty"`
}

func (x *GetMyDogMessage) Reset() {
	*x = GetMyDogMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyDogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyDogMessage) ProtoMessage() {}

func (x *GetMyDogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyDogMessage.ProtoReflect.Descriptor instead.
func (*GetMyDogMessage) Descriptor() ([]byte, []int) {
	return file_dog_proto_rawDescGZIP(), []int{0}
}

func (x *GetMyDogMessage) GetTargetDog() string {
	if x != nil {
		return x.TargetDog
	}
	return ""
}

type GetMyDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *GetMyDogResponse) Reset() {
	*x = GetMyDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyDogResponse) ProtoMessage() {}

func (x *GetMyDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyDogResponse.ProtoReflect.Descriptor instead.
func (*GetMyDogResponse) Descriptor() ([]byte, []int) {
	return file_dog_proto_rawDescGZIP(), []int{1}
}

func (x *GetMyDogResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMyDogResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

var File_dog_proto protoreflect.FileDescriptor

var file_dog_proto_rawDesc = []byte{
	0x0a, 0x09, 0x64, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x64, 0x6f, 0x67,
	0x22, 0x30, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x64, 0x6f,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x44,
	0x6f, 0x67, 0x22, 0x3a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x32, 0x40,
	0x0a, 0x03, 0x44, 0x6f, 0x67, 0x12, 0x39, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x44, 0x6f,
	0x67, 0x12, 0x14, 0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x44, 0x6f, 0x67,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x15, 0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dog_proto_rawDescOnce sync.Once
	file_dog_proto_rawDescData = file_dog_proto_rawDesc
)

func file_dog_proto_rawDescGZIP() []byte {
	file_dog_proto_rawDescOnce.Do(func() {
		file_dog_proto_rawDescData = protoimpl.X.CompressGZIP(file_dog_proto_rawDescData)
	})
	return file_dog_proto_rawDescData
}

var file_dog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dog_proto_goTypes = []interface{}{
	(*GetMyDogMessage)(nil),  // 0: dog.GetMyDogMessage
	(*GetMyDogResponse)(nil), // 1: dog.GetMyDogResponse
}
var file_dog_proto_depIdxs = []int32{
	0, // 0: dog.Dog.GetMyDog:input_type -> dog.GetMyDogMessage
	1, // 1: dog.Dog.GetMyDog:output_type -> dog.GetMyDogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dog_proto_init() }
func file_dog_proto_init() {
	if File_dog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyDogMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dog_proto_goTypes,
		DependencyIndexes: file_dog_proto_depIdxs,
		MessageInfos:      file_dog_proto_msgTypes,
	}.Build()
	File_dog_proto = out.File
	file_dog_proto_rawDesc = nil
	file_dog_proto_goTypes = nil
	file_dog_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DogClient is the client API for Dog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DogClient interface {
	GetMyDog(ctx context.Context, in *GetMyDogMessage, opts ...grpc.CallOption) (*GetMyDogResponse, error)
}

type dogClient struct {
	cc grpc.ClientConnInterface
}

func NewDogClient(cc grpc.ClientConnInterface) DogClient {
	return &dogClient{cc}
}

func (c *dogClient) GetMyDog(ctx context.Context, in *GetMyDogMessage, opts ...grpc.CallOption) (*GetMyDogResponse, error) {
	out := new(GetMyDogResponse)
	err := c.cc.Invoke(ctx, "/dog.Dog/GetMyDog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DogServer is the server API for Dog service.
type DogServer interface {
	GetMyDog(context.Context, *GetMyDogMessage) (*GetMyDogResponse, error)
}

// UnimplementedDogServer can be embedded to have forward compatible implementations.
type UnimplementedDogServer struct {
}

func (*UnimplementedDogServer) GetMyDog(context.Context, *GetMyDogMessage) (*GetMyDogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyDog not implemented")
}

func RegisterDogServer(s *grpc.Server, srv DogServer) {
	s.RegisterService(&_Dog_serviceDesc, srv)
}

func _Dog_GetMyDog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyDogMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DogServer).GetMyDog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dog.Dog/GetMyDog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DogServer).GetMyDog(ctx, req.(*GetMyDogMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dog.Dog",
	HandlerType: (*DogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyDog",
			Handler:    _Dog_GetMyDog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dog.proto",
}
