// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.1
// source: dog.proto

package dog

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetMyDogMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetDog string `protobuf:"bytes,1,opt,name=target_dog,json=targetDog,proto3" json:"target_dog,omitempty"`
}

func (x *GetMyDogMessage) Reset() {
	*x = GetMyDogMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyDogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyDogMessage) ProtoMessage() {}

func (x *GetMyDogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyDogMessage.ProtoReflect.Descriptor instead.
func (*GetMyDogMessage) Descriptor() ([]byte, []int) {
	return file_dog_proto_rawDescGZIP(), []int{0}
}

func (x *GetMyDogMessage) GetTargetDog() string {
	if x != nil {
		return x.TargetDog
	}
	return ""
}

type GetMyDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *GetMyDogResponse) Reset() {
	*x = GetMyDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyDogResponse) ProtoMessage() {}

func (x *GetMyDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyDogResponse.ProtoReflect.Descriptor instead.
func (*GetMyDogResponse) Descriptor() ([]byte, []int) {
	return file_dog_proto_rawDescGZIP(), []int{1}
}

func (x *GetMyDogResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMyDogResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type AddMyDogMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *AddMyDogMessage) Reset() {
	*x = AddMyDogMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMyDogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMyDogMessage) ProtoMessage() {}

func (x *AddMyDogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMyDogMessage.ProtoReflect.Descriptor instead.
func (*AddMyDogMessage) Descriptor() ([]byte, []int) {
	return file_dog_proto_rawDescGZIP(), []int{2}
}

func (x *AddMyDogMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddMyDogMessage) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type AddMyDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AddMyDogResponse) Reset() {
	*x = AddMyDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dog_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMyDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMyDogResponse) ProtoMessage() {}

func (x *AddMyDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dog_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMyDogResponse.ProtoReflect.Descriptor instead.
func (*AddMyDogResponse) Descriptor() ([]byte, []int) {
	return file_dog_proto_rawDescGZIP(), []int{3}
}

func (x *AddMyDogResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type UpdateMyDogMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind   string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Remark string `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *UpdateMyDogMessage) Reset() {
	*x = UpdateMyDogMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dog_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMyDogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMyDogMessage) ProtoMessage() {}

func (x *UpdateMyDogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dog_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMyDogMessage.ProtoReflect.Descriptor instead.
func (*UpdateMyDogMessage) Descriptor() ([]byte, []int) {
	return file_dog_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMyDogMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMyDogMessage) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UpdateMyDogMessage) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type UpdateMyDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *UpdateMyDogResponse) Reset() {
	*x = UpdateMyDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dog_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMyDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMyDogResponse) ProtoMessage() {}

func (x *UpdateMyDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dog_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMyDogResponse.ProtoReflect.Descriptor instead.
func (*UpdateMyDogResponse) Descriptor() ([]byte, []int) {
	return file_dog_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMyDogResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type DeleteMyDogMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *DeleteMyDogMessage) Reset() {
	*x = DeleteMyDogMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dog_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMyDogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMyDogMessage) ProtoMessage() {}

func (x *DeleteMyDogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dog_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMyDogMessage.ProtoReflect.Descriptor instead.
func (*DeleteMyDogMessage) Descriptor() ([]byte, []int) {
	return file_dog_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteMyDogMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteMyDogMessage) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type DeleteMyDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DeleteMyDogResponse) Reset() {
	*x = DeleteMyDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dog_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMyDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMyDogResponse) ProtoMessage() {}

func (x *DeleteMyDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dog_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMyDogResponse.ProtoReflect.Descriptor instead.
func (*DeleteMyDogResponse) Descriptor() ([]byte, []int) {
	return file_dog_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMyDogResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_dog_proto protoreflect.FileDescriptor

var file_dog_proto_rawDesc = []byte{
	0x0a, 0x09, 0x64, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x64, 0x6f, 0x67,
	0x22, 0x30, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x64, 0x6f,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x44,
	0x6f, 0x67, 0x22, 0x3a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x39,
	0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x2a, 0x0a, 0x10, 0x41, 0x64, 0x64,
	0x4d, 0x79, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x54, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x79, 0x44, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x2d, 0x0a, 0x13, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3c, 0x0a, 0x12, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x2d, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x83, 0x02, 0x0a, 0x03, 0x44, 0x6f, 0x67, 0x12,
	0x39, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x12, 0x14, 0x2e, 0x64, 0x6f,
	0x67, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x15, 0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x44, 0x6f, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x08, 0x41, 0x64,
	0x64, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x12, 0x14, 0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x41, 0x64, 0x64,
	0x4d, 0x79, 0x44, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x15, 0x2e, 0x64,
	0x6f, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x79, 0x44, 0x6f, 0x67, 0x12, 0x17, 0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x18, 0x2e,
	0x64, 0x6f, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x12, 0x17, 0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x79, 0x44, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x18, 0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x79,
	0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dog_proto_rawDescOnce sync.Once
	file_dog_proto_rawDescData = file_dog_proto_rawDesc
)

func file_dog_proto_rawDescGZIP() []byte {
	file_dog_proto_rawDescOnce.Do(func() {
		file_dog_proto_rawDescData = protoimpl.X.CompressGZIP(file_dog_proto_rawDescData)
	})
	return file_dog_proto_rawDescData
}

var file_dog_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_dog_proto_goTypes = []interface{}{
	(*GetMyDogMessage)(nil),     // 0: dog.GetMyDogMessage
	(*GetMyDogResponse)(nil),    // 1: dog.GetMyDogResponse
	(*AddMyDogMessage)(nil),     // 2: dog.AddMyDogMessage
	(*AddMyDogResponse)(nil),    // 3: dog.AddMyDogResponse
	(*UpdateMyDogMessage)(nil),  // 4: dog.UpdateMyDogMessage
	(*UpdateMyDogResponse)(nil), // 5: dog.UpdateMyDogResponse
	(*DeleteMyDogMessage)(nil),  // 6: dog.DeleteMyDogMessage
	(*DeleteMyDogResponse)(nil), // 7: dog.DeleteMyDogResponse
}
var file_dog_proto_depIdxs = []int32{
	0, // 0: dog.Dog.GetMyDog:input_type -> dog.GetMyDogMessage
	2, // 1: dog.Dog.AddMyDog:input_type -> dog.AddMyDogMessage
	4, // 2: dog.Dog.UpdateMyDog:input_type -> dog.UpdateMyDogMessage
	6, // 3: dog.Dog.DeleteMyDog:input_type -> dog.DeleteMyDogMessage
	1, // 4: dog.Dog.GetMyDog:output_type -> dog.GetMyDogResponse
	3, // 5: dog.Dog.AddMyDog:output_type -> dog.AddMyDogResponse
	5, // 6: dog.Dog.UpdateMyDog:output_type -> dog.UpdateMyDogResponse
	7, // 7: dog.Dog.DeleteMyDog:output_type -> dog.DeleteMyDogResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dog_proto_init() }
func file_dog_proto_init() {
	if File_dog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyDogMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMyDogMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dog_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMyDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dog_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMyDogMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dog_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMyDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dog_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMyDogMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dog_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMyDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dog_proto_goTypes,
		DependencyIndexes: file_dog_proto_depIdxs,
		MessageInfos:      file_dog_proto_msgTypes,
	}.Build()
	File_dog_proto = out.File
	file_dog_proto_rawDesc = nil
	file_dog_proto_goTypes = nil
	file_dog_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DogClient is the client API for Dog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DogClient interface {
	GetMyDog(ctx context.Context, in *GetMyDogMessage, opts ...grpc.CallOption) (*GetMyDogResponse, error)
	AddMyDog(ctx context.Context, in *AddMyDogMessage, opts ...grpc.CallOption) (*AddMyDogResponse, error)
	UpdateMyDog(ctx context.Context, in *UpdateMyDogMessage, opts ...grpc.CallOption) (*UpdateMyDogResponse, error)
	DeleteMyDog(ctx context.Context, in *DeleteMyDogMessage, opts ...grpc.CallOption) (*DeleteMyDogResponse, error)
}

type dogClient struct {
	cc grpc.ClientConnInterface
}

func NewDogClient(cc grpc.ClientConnInterface) DogClient {
	return &dogClient{cc}
}

func (c *dogClient) GetMyDog(ctx context.Context, in *GetMyDogMessage, opts ...grpc.CallOption) (*GetMyDogResponse, error) {
	out := new(GetMyDogResponse)
	err := c.cc.Invoke(ctx, "/dog.Dog/GetMyDog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dogClient) AddMyDog(ctx context.Context, in *AddMyDogMessage, opts ...grpc.CallOption) (*AddMyDogResponse, error) {
	out := new(AddMyDogResponse)
	err := c.cc.Invoke(ctx, "/dog.Dog/AddMyDog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dogClient) UpdateMyDog(ctx context.Context, in *UpdateMyDogMessage, opts ...grpc.CallOption) (*UpdateMyDogResponse, error) {
	out := new(UpdateMyDogResponse)
	err := c.cc.Invoke(ctx, "/dog.Dog/UpdateMyDog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dogClient) DeleteMyDog(ctx context.Context, in *DeleteMyDogMessage, opts ...grpc.CallOption) (*DeleteMyDogResponse, error) {
	out := new(DeleteMyDogResponse)
	err := c.cc.Invoke(ctx, "/dog.Dog/DeleteMyDog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DogServer is the server API for Dog service.
type DogServer interface {
	GetMyDog(context.Context, *GetMyDogMessage) (*GetMyDogResponse, error)
	AddMyDog(context.Context, *AddMyDogMessage) (*AddMyDogResponse, error)
	UpdateMyDog(context.Context, *UpdateMyDogMessage) (*UpdateMyDogResponse, error)
	DeleteMyDog(context.Context, *DeleteMyDogMessage) (*DeleteMyDogResponse, error)
}

// UnimplementedDogServer can be embedded to have forward compatible implementations.
type UnimplementedDogServer struct {
}

func (*UnimplementedDogServer) GetMyDog(context.Context, *GetMyDogMessage) (*GetMyDogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyDog not implemented")
}
func (*UnimplementedDogServer) AddMyDog(context.Context, *AddMyDogMessage) (*AddMyDogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMyDog not implemented")
}
func (*UnimplementedDogServer) UpdateMyDog(context.Context, *UpdateMyDogMessage) (*UpdateMyDogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMyDog not implemented")
}
func (*UnimplementedDogServer) DeleteMyDog(context.Context, *DeleteMyDogMessage) (*DeleteMyDogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMyDog not implemented")
}

func RegisterDogServer(s *grpc.Server, srv DogServer) {
	s.RegisterService(&_Dog_serviceDesc, srv)
}

func _Dog_GetMyDog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyDogMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DogServer).GetMyDog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dog.Dog/GetMyDog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DogServer).GetMyDog(ctx, req.(*GetMyDogMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dog_AddMyDog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMyDogMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DogServer).AddMyDog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dog.Dog/AddMyDog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DogServer).AddMyDog(ctx, req.(*AddMyDogMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dog_UpdateMyDog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMyDogMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DogServer).UpdateMyDog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dog.Dog/UpdateMyDog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DogServer).UpdateMyDog(ctx, req.(*UpdateMyDogMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dog_DeleteMyDog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMyDogMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DogServer).DeleteMyDog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dog.Dog/DeleteMyDog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DogServer).DeleteMyDog(ctx, req.(*DeleteMyDogMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dog.Dog",
	HandlerType: (*DogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyDog",
			Handler:    _Dog_GetMyDog_Handler,
		},
		{
			MethodName: "AddMyDog",
			Handler:    _Dog_AddMyDog_Handler,
		},
		{
			MethodName: "UpdateMyDog",
			Handler:    _Dog_UpdateMyDog_Handler,
		},
		{
			MethodName: "DeleteMyDog",
			Handler:    _Dog_DeleteMyDog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dog.proto",
}
